// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN0w8KAANf3ZBbdg8gnhSARidAeP0f2p0',
    appId: '1:325621015091:web:110ab7c237c6a4ddb2f946',
    messagingSenderId: '325621015091',
    projectId: 'one-piece-card-database',
    authDomain: 'one-piece-card-database.firebaseapp.com',
    storageBucket: 'one-piece-card-database.firebasestorage.app',
    measurementId: 'G-7G5Q9P7GEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvidA4cvPeAcFzJgCWcwavbpgfpZVvBFA',
    appId: '1:325621015091:android:8698e3e573c90c4bb2f946',
    messagingSenderId: '325621015091',
    projectId: 'one-piece-card-database',
    storageBucket: 'one-piece-card-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNsPsyjA2CxSG2Y-K69dil7Vn5wNY1y0',
    appId: '1:325621015091:ios:dd43a8465895715cb2f946',
    messagingSenderId: '325621015091',
    projectId: 'one-piece-card-database',
    storageBucket: 'one-piece-card-database.firebasestorage.app',
    iosBundleId: 'com.example.onepieceInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASNsPsyjA2CxSG2Y-K69dil7Vn5wNY1y0',
    appId: '1:325621015091:ios:dd43a8465895715cb2f946',
    messagingSenderId: '325621015091',
    projectId: 'one-piece-card-database',
    storageBucket: 'one-piece-card-database.firebasestorage.app',
    iosBundleId: 'com.example.onepieceInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN0w8KAANf3ZBbdg8gnhSARidAeP0f2p0',
    appId: '1:325621015091:web:d8acf8a0c85a94edb2f946',
    messagingSenderId: '325621015091',
    projectId: 'one-piece-card-database',
    authDomain: 'one-piece-card-database.firebaseapp.com',
    storageBucket: 'one-piece-card-database.firebasestorage.app',
    measurementId: 'G-VPG4X9LCC8',
  );
}
